[package]
name = "edisch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
dialoguer = "0.11.0"
regex = "1.10.5"
serenity = "0.12.2"
tokio = { version = "1.38.0", features = ["full"] }
